# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Datas_pb2 as Datas__pb2


class MainServerStub(object):
    """responce server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getImage = channel.unary_stream(
                '/MainServer/getImage',
                request_serializer=Datas__pb2.ImageRequest.SerializeToString,
                response_deserializer=Datas__pb2.ImageReply.FromString,
                )


class MainServerServicer(object):
    """responce server
    """

    def getImage(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MainServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getImage': grpc.unary_stream_rpc_method_handler(
                    servicer.getImage,
                    request_deserializer=Datas__pb2.ImageRequest.FromString,
                    response_serializer=Datas__pb2.ImageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MainServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MainServer(object):
    """responce server
    """

    @staticmethod
    def getImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/MainServer/getImage',
            Datas__pb2.ImageRequest.SerializeToString,
            Datas__pb2.ImageReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
